import { supabase } from './supabase'
import { currentUserId } from './modules'

export type MedicationInput={medicine_name:string;medicine_form:string;strength:string;dosage:string;frequency:string;duration:string;quantity:string;instructions:string}
export type Prescription={id:string;patient_id:string;doctor_id:string;diagnosis:string|null;clinical_notes:string|null;status:'active'|'completed'|'cancelled';prescribed_at:string;prescription_medications:Array<MedicationInput&{id:string}>;patientName?:string;doctorName?:string}

export async function carePatients(){const doctorId=await currentUserId();const {data:links,error}=await supabase.from('conversations').select('patient_id').eq('doctor_id',doctorId);if(error)throw error;const ids=[...new Set((links??[]).map(row=>row.patient_id))];if(!ids.length)return[];const {data,error:profileError}=await supabase.from('profiles').select('id,full_name').in('id',ids).order('full_name');if(profileError)throw profileError;return data??[]}
export async function getPrescriptions(role:'patient'|'doctor'){const userId=await currentUserId();const column=role==='patient'?'patient_id':'doctor_id';const {data,error}=await supabase.from('prescriptions').select('id,patient_id,doctor_id,diagnosis,clinical_notes,status,prescribed_at,prescription_medications(id,medicine_name,medicine_form,strength,dosage,frequency,duration,quantity,instructions)').eq(column,userId).order('prescribed_at',{ascending:false});if(error)throw error;const rows=(data??[]) as Prescription[];if(role==='doctor'){const ids=[...new Set(rows.map(r=>r.patient_id))];if(ids.length){const {data:people}=await supabase.from('profiles').select('id,full_name').in('id',ids);const names=new Map<string,string>((people??[]).map(p=>[String(p.id),String(p.full_name)]));rows.forEach(r=>r.patientName=names.get(r.patient_id)||'Patient')}}else{const {data:doctors}=await supabase.rpc('list_verified_doctors');const names=new Map<string,string>(((doctors??[]) as Array<{id:string;full_name:string}>).map(p=>[p.id,p.full_name]));rows.forEach(r=>r.doctorName=names.get(r.doctor_id)||'Your doctor')}return rows}
export async function createPrescription(patientId:string,diagnosis:string,notes:string,medications:MedicationInput[]){const {error}=await supabase.rpc('create_prescription',{target_patient:patientId,diagnosis_text:diagnosis,notes_text:notes,medications});if(error)throw error}
export async function completePrescription(id:string){const {error}=await supabase.from('prescriptions').update({status:'completed'}).eq('id',id);if(error)throw error}
export async function updatePrescription(id:string,diagnosis:string,notes:string,medications:MedicationInput[]){const {error}=await supabase.rpc('update_prescription',{prescription_uuid:id,diagnosis_text:diagnosis,notes_text:notes,medications});if(error)throw error}
