import { useEffect, useRef, useState, type ChangeEvent, type FormEvent } from 'react'
import AppLayout from '../components/AppLayout'
import { listChats, loadChat, markChatRead, otherIsTyping, sendMedia, sendText, setTyping, subscribeChat, type ChatConversation, type ChatMessage, type ChatType } from '../services/chat'
import type { UserRole } from '../types/auth'

type FailedUpload={file:File;type:Exclude<ChatType,'text'>;error:string;duration?:number}
const prettySize=(bytes:number|null)=>bytes?bytes<1048576?`${(bytes/1024).toFixed(0)} KB`:`${(bytes/1048576).toFixed(1)} MB`:''
const time=(value:string)=>new Date(value).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})
function FormattedText({text}:{text:string}){return <>{text.split('\n').map((line,i)=><span key={i}>{line.split(/(\*\*[^*]+\*\*)/).map((part,j)=>part.startsWith('**')?<strong key={j}>{part.slice(2,-2)}</strong>:part)}{i<text.split('\n').length-1&&<br/>}</span>)}</>}

export default function ChatPage({role}:{role:Exclude<UserRole,'admin'>}){
  const [chats,setChats]=useState<ChatConversation[]>([]),[active,setActive]=useState<ChatConversation|null>(null),[messages,setMessages]=useState<ChatMessage[]>([])
  const [userId,setUserId]=useState(''),[draft,setDraft]=useState(''),[remoteTyping,setRemoteTyping]=useState(false),[picker,setPicker]=useState(false),[upload,setUpload]=useState(0),[error,setError]=useState(''),[failed,setFailed]=useState<FailedUpload|null>(null),[preview,setPreview]=useState<ChatMessage|null>(null),[recording,setRecording]=useState(false)
  const endRef=useRef<HTMLDivElement>(null),typingTimer=useRef<number|undefined>(undefined),recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),recordStart=useRef(0)

  async function refreshList(selectFirst=false){const data=await listChats();setUserId(data.userId);setChats(data.conversations);if(selectFirst&&!active&&data.conversations[0])setActive(data.conversations[0])}
  async function refreshMessages(){if(!active)return;const data=await loadChat(active.id);setMessages(data);await markChatRead(active.id,userId);setTimeout(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),30)}
  useEffect(()=>{refreshList(true).catch(e=>setError(e.message))},[])
  useEffect(()=>{if(!active||!userId)return;refreshMessages().catch(e=>setError(e.message));const stop=subscribeChat(active.id,()=>{refreshMessages();refreshList()},async()=>setRemoteTyping(await otherIsTyping(active.id,userId)));return()=>{stop();setTyping(active.id,false).catch(()=>{})}},[active?.id,userId])

  async function submit(event:FormEvent){event.preventDefault();if(!active||!draft.trim())return;const text=draft;setDraft('');setTyping(active.id,false).catch(()=>{});try{await sendText(active.id,text);await refreshMessages()}catch(e){setDraft(text);setError(e instanceof Error?e.message:'Message failed to send.') }}
  function typeDraft(value:string){setDraft(value);if(!active)return;setTyping(active.id,true).catch(()=>{});window.clearTimeout(typingTimer.current);typingTimer.current=window.setTimeout(()=>setTyping(active.id,false).catch(()=>{}),1800)}
  function validate(file:File,type:Exclude<ChatType,'text'>){const max=type==='image'?10:25;if(file.size>max*1048576)throw new Error(`${type==='image'?'Images':'Files'} must be under ${max} MB.`);if(type==='image'&&!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG, or WebP image.');if(type==='pdf'&&file.type!=='application/pdf')throw new Error('Choose a PDF document.');if(type==='video'&&!file.type.startsWith('video/'))throw new Error('Choose a video file.')}
  async function uploadFile(file:File,type:Exclude<ChatType,'text'>,duration?:number){if(!active)return;try{validate(file,type);setFailed(null);setError('');setUpload(12);const timer=window.setInterval(()=>setUpload(v=>Math.min(v+9,88)),180);await sendMedia(active.id,file,type,duration);window.clearInterval(timer);setUpload(100);await refreshMessages();window.setTimeout(()=>setUpload(0),500)}catch(e){setUpload(0);const message=e instanceof Error?e.message:'Upload failed.';setFailed({file,type,error:message,duration});setError(message)}}
  function chooseFile(event:ChangeEvent<HTMLInputElement>,type:Exclude<ChatType,'text'>){const file=event.target.files?.[0];if(file)uploadFile(file,type);event.target.value='';setPicker(false)}
  async function toggleRecording(){if(recording){recorder.current?.stop();return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const media=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':undefined});chunks.current=[];media.ondataavailable=e=>chunks.current.push(e.data);media.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const duration=Math.max(1,Math.round((Date.now()-recordStart.current)/1000));const file=new File(chunks.current,`voice-${Date.now()}.webm`,{type:'audio/webm'});setRecording(false);uploadFile(file,'voice',duration)};recordStart.current=Date.now();recorder.current=media;media.start();setRecording(true);setPicker(false)}catch{setError('Microphone permission is required to record a voice message.')}}

  return <AppLayout role={role}><main className={`chat-page ${active?'conversation-open':''}`}>
    <aside className="chat-list"><header><div><p>SECURE MESSAGES</p><h1>Conversations</h1></div><span>{chats.length}</span></header><div className="chat-search">⌕ <input placeholder="Search conversations" /></div><div className="chat-list-items">{chats.map(chat=><button key={chat.id} className={active?.id===chat.id?'active':''} onClick={()=>setActive(chat)}><span className="chat-person">{chat.otherName.split(/\s+/).slice(0,2).map(n=>n[0]).join('')}</span><span><b>{chat.otherName}</b><small>{chat.lastMessage}</small></span><time>{new Date(chat.updated_at).toLocaleDateString([],{month:'short',day:'numeric'})}</time>{chat.unread>0&&<i>{chat.unread}</i>}</button>)}{!chats.length&&<div className="chat-list-empty"><b>No conversations yet</b><p>Your active patient-doctor conversations will appear here.</p></div>}</div></aside>
    <section className="chat-thread">{active?<><header className="chat-thread-head"><button className="chat-back" onClick={()=>setActive(null)}>←</button><span className="chat-person">{active.otherName.split(/\s+/).slice(0,2).map(n=>n[0]).join('')}</span><div><b>{active.otherName}</b><small><i/> {active.otherRole} · Secure conversation</small></div><span className="encrypted">▣ Encrypted</span></header>
      <div className="message-area">{!messages.length?<div className="message-empty"><span>✦</span><h2>Start the conversation</h2><p>Messages and shared medical files are visible only to you and {active.otherName}.</p></div>:messages.map(message=><article key={message.id} className={`message-row ${message.sender_id===userId?'mine':'theirs'}`}><div className={`message-bubble ${message.type}`}>
        {message.type==='text'&&<p><FormattedText text={message.body||''}/></p>}
        {message.type==='image'&&<button className="image-message" onClick={()=>setPreview(message)}><img src={message.mediaUrl} alt={message.file_name||'Shared image'}/></button>}
        {message.type==='video'&&<video src={message.mediaUrl} controls preload="metadata"/>}
        {message.type==='voice'&&<div className="voice-message"><span>▶</span><audio src={message.mediaUrl} controls preload="metadata"/><small>{message.duration_seconds||0}s</small></div>}
        {message.type==='pdf'&&<a className="pdf-message" href={message.mediaUrl} target="_blank" rel="noreferrer"><span>PDF</span><div><b>{message.file_name}</b><small>{prettySize(message.file_size)} · Preview or download</small></div><i>↓</i></a>}
        <footer><time>{time(message.sent_at)}</time>{message.sender_id===userId&&<span title={message.status}>{message.read_at?'✓✓':message.delivered_at?'✓✓':'✓'}</span>}</footer>
      </div></article>)}{remoteTyping&&<div className="typing-bubble"><i/><i/><i/> {active.otherName} is typing…</div>}<div ref={endRef}/></div>
      {failed&&<div className="upload-error"><span>Upload failed: {failed.file.name}</span><button onClick={()=>uploadFile(failed.file,failed.type,failed.duration)}>Retry</button><button onClick={()=>setFailed(null)}>Dismiss</button></div>}{upload>0&&<div className="upload-progress"><span style={{width:`${upload}%`}}/><b>Uploading securely… {upload}%</b></div>}
      <form className="chat-composer" onSubmit={submit}><div className="attachment-wrap"><button type="button" className="attach-button" onClick={()=>setPicker(v=>!v)}>＋</button>{picker&&<div className="attachment-menu"><label>📷 Camera<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>chooseFile(e,'image')}/></label><label>🖼 Gallery<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseFile(e,'image')}/></label><label>PDF Document<input type="file" accept="application/pdf" onChange={e=>chooseFile(e,'pdf')}/></label><label>▶ Video<input type="file" accept="video/mp4,video/webm,video/quicktime" onChange={e=>chooseFile(e,'video')}/></label></div>}</div><textarea rows={1} value={draft} onChange={e=>typeDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} placeholder="Write a message…"/><button type="button" className={`record-button ${recording?'recording':''}`} onClick={toggleRecording}>{recording?'■':'●'}</button><button className="send-button" disabled={!draft.trim()}>➤</button></form></>:<div className="select-chat"><span>✦</span><h2>Select a conversation</h2><p>Choose a patient or doctor from the conversation list to begin secure messaging.</p></div>}</section>
    {preview&&<div className="media-preview" onClick={()=>setPreview(null)}><button>×</button><img src={preview.mediaUrl} alt={preview.file_name||'Image preview'}/><p>{preview.file_name}</p></div>}
    {error&&<div className="chat-toast" onClick={()=>setError('')}>{error}<button>×</button></div>}
  </main></AppLayout>
}
