import { useEffect, useState, type FormEvent } from 'react'
import AppLayout from '../components/AppLayout'
import { reports } from '../services/modules'
import { carePatients, completePrescription, createPrescription, getPrescriptions, type MedicationInput, type Prescription } from '../services/prescriptions'
import type { UserRole } from '../types/auth'

const medication=():MedicationInput=>({medicine_name:'',medicine_form:'tablet',strength:'',dosage:'',frequency:'',duration:'',quantity:'',instructions:''})
const forms=[['tablet','Tablet'],['capsule','Capsule'],['syrup','Syrup'],['injection','Injection'],['cream','Cream'],['drops','Drops'],['inhaler','Inhaler'],['other','Other']]

export default function ReportsPage({role}:{role:Exclude<UserRole,'admin'>}){
  const [prescriptions,setPrescriptions]=useState<Prescription[]>([]),[reportItems,setReportItems]=useState<any[]>([]),[patients,setPatients]=useState<Array<{id:string;full_name:string}>>([]),[medications,setMedications]=useState<MedicationInput[]>([medication()]),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
  async function refresh(){const [rx,reportsData]=await Promise.all([getPrescriptions(role),reports()]);setPrescriptions(rx);setReportItems(reportsData);if(role==='doctor')setPatients(await carePatients())}
  useEffect(()=>{refresh().catch(e=>setNotice(e.message))},[role])
  function updateMedication(index:number,key:keyof MedicationInput,value:string){setMedications(items=>items.map((item,i)=>i===index?{...item,[key]:value}:item))}
  async function prescribe(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,values=new FormData(form);setSaving(true);setNotice('');try{await createPrescription(String(values.get('patient')),String(values.get('diagnosis')),String(values.get('notes')),medications);form.reset();setMedications([medication()]);setNotice('Prescription saved securely and is now visible to the patient.');await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Unable to save prescription.')}finally{setSaving(false)}}
  function downloadCsv(){const header=['patient','doctor','diagnosis','medicine','form','strength','dosage','frequency','duration','instructions','prescribed_at'];const rows=prescriptions.flatMap(rx=>rx.prescription_medications.map(m=>[rx.patientName||'',rx.doctorName||'',rx.diagnosis||'',m.medicine_name,m.medicine_form,m.strength,m.dosage,m.frequency,m.duration,m.instructions,rx.prescribed_at]));const csv=[header,...rows].map(row=>row.map(value=>JSON.stringify(value??'')).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='medlink-medical-records.csv';a.click();URL.revokeObjectURL(a.href)}
  function printPdf(){window.print()}
  async function finish(id:string){try{await completePrescription(id);await refresh()}catch(e){setNotice(e instanceof Error?e.message:'Unable to update prescription.')}}
  return <AppLayout role={role}><main className="feature-page records-page"><header className="records-hero"><div><p className="eyebrow">MEDICAL RECORDS</p><h1>{role==='doctor'?'Prescribe and manage treatment':'Your prescriptions and reports'}</h1><p className="feature-note">{role==='doctor'?'Create private medication plans for each patient in your care.':'Review medication instructions shared securely by your doctor.'}</p></div><div className="report-actions"><button className="outline" onClick={downloadCsv}>Download CSV</button><button className="primary" onClick={printPdf}>Print / Save PDF</button></div></header>
    {notice&&<div className="records-notice">{notice}</div>}
    <div className={`records-layout ${role}`}>
      {role==='doctor'&&<section className="module-card prescription-composer"><div className="records-section-title"><span>Rx</span><div><h2>New prescription</h2><p>Only you and the selected patient can access this record.</p></div></div>
        <form onSubmit={prescribe} className="prescription-form"><label>Patient<select name="patient" required defaultValue=""><option value="">Choose one of your patients</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.full_name}</option>)}</select></label><label>Diagnosis or reason<input name="diagnosis" placeholder="e.g. Bacterial throat infection" /></label><label>Clinical note<textarea name="notes" placeholder="Private treatment note for this patient"/></label>
          <div className="medicine-heading"><h3>Medicines</h3><button type="button" onClick={()=>setMedications(items=>[...items,medication()])}>＋ Add medicine</button></div>
          {medications.map((item,index)=><fieldset className="medicine-editor" key={index}><legend>Medicine {index+1}</legend>{medications.length>1&&<button type="button" className="remove-medicine" onClick={()=>setMedications(items=>items.filter((_,i)=>i!==index))}>Remove</button>}<label className="medicine-name">Medicine name<input required value={item.medicine_name} onChange={e=>updateMedication(index,'medicine_name',e.target.value)} placeholder="e.g. Amoxicillin"/></label><label>Form<select value={item.medicine_form} onChange={e=>updateMedication(index,'medicine_form',e.target.value)}>{forms.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Strength<input value={item.strength} onChange={e=>updateMedication(index,'strength',e.target.value)} placeholder="e.g. 500 mg"/></label><label>Dosage<input required value={item.dosage} onChange={e=>updateMedication(index,'dosage',e.target.value)} placeholder="e.g. 1 tablet"/></label><label>Frequency<input required value={item.frequency} onChange={e=>updateMedication(index,'frequency',e.target.value)} placeholder="e.g. Twice daily"/></label><label>Duration<input required value={item.duration} onChange={e=>updateMedication(index,'duration',e.target.value)} placeholder="e.g. 7 days"/></label><label>Quantity<input value={item.quantity} onChange={e=>updateMedication(index,'quantity',e.target.value)} placeholder="e.g. 14 tablets"/></label><label className="medicine-instructions">Patient instructions<textarea value={item.instructions} onChange={e=>updateMedication(index,'instructions',e.target.value)} placeholder="e.g. Take after food and finish the course"/></label></fieldset>)}
          <button className="primary prescribe-button" disabled={saving||!patients.length}>{saving?'Saving securely…':'Issue prescription'}</button>{!patients.length&&<small className="no-patients">No linked patients yet. A patient appears here after starting a consultation with you.</small>}
        </form></section>}
      <section className="prescription-history"><div className="history-heading"><div><p className="eyebrow">TREATMENT HISTORY</p><h2>{role==='doctor'?'Prescriptions you issued':'My medication plans'}</h2></div><span>{prescriptions.length} records</span></div>
        {prescriptions.length?prescriptions.map(rx=><article className="prescription-card" key={rx.id}><header><div className="rx-symbol">Rx</div><div><h3>{role==='doctor'?rx.patientName:rx.doctorName}</h3><p>{rx.diagnosis||'Medication prescription'} · {new Date(rx.prescribed_at).toLocaleDateString()}</p></div><span className={`rx-status ${rx.status}`}>{rx.status}</span></header><div className="medicine-list">{rx.prescription_medications.map(m=><div className="medicine-row" key={m.id}><span className={`medicine-form-icon ${m.medicine_form}`}>{m.medicine_form==='syrup'?'♧':'✚'}</span><div><h4>{m.medicine_name} {m.strength&&<small>{m.strength}</small>}</h4><p><b>{m.dosage}</b> · {m.frequency} · {m.duration}</p>{m.quantity&&<p>Quantity: {m.quantity}</p>}{m.instructions&&<em>{m.instructions}</em>}</div></div>)}</div>{rx.clinical_notes&&<div className="clinical-note"><b>Clinical note</b><p>{rx.clinical_notes}</p></div>}{role==='doctor'&&rx.status==='active'&&<button className="outline complete-rx" onClick={()=>finish(rx.id)}>Mark treatment completed</button>}</article>):<div className="module-card records-empty"><span>Rx</span><h3>No prescriptions yet</h3><p>{role==='doctor'?'Prescriptions you create will appear here.':'Your doctor has not issued a prescription yet.'}</p></div>}
        {reportItems.length>0&&<section className="module-card legacy-reports"><h2>Medical reports</h2>{reportItems.map(report=><div className="thread" key={report.id}><b>{report.title}</b><small>{new Date(report.created_at).toLocaleDateString()}</small><p>{report.summary}</p></div>)}</section>}
      </section>
    </div>
  </main></AppLayout>}
