import { useEffect, useRef, useState } from 'react'
import AppLayout from '../../components/AppLayout'
import { currentUserId, doctors, requestAppointment, sendMessage } from '../../services/modules'

export default function PatientModule() { const [list,setList]=useState<any[]>([]); const [message,setMessage]=useState(''); const [recording,setRecording]=useState(false); const recorder=useRef<MediaRecorder | null>(null);
useEffect(()=>{doctors().then(setList).catch(e=>setMessage(e.message))},[])
async function book(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await requestAppointment(String(f.get('doctor')),String(f.get('time')),String(f.get('reason')));setMessage('Appointment request sent.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to request appointment.')}}
async function record(){if(recording){recorder.current?.stop();setRecording(false);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);const chunks:Blob[]=[];r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setMessage(`Voice note recorded (${Math.ceil(new Blob(chunks).size/1024)} KB). Select a conversation to send it.`)};r.start();recorder.current=r;setRecording(true)}catch{setMessage('Microphone permission is required for voice notes.')}}
  return <AppLayout role="patient"><main className="feature-page"><p className="eyebrow">PATIENT CARE</p><h1>Find care and manage consultations</h1><p className="feature-note">Search verified doctors, request a time, then continue securely in your consultation thread.</p><div className="module-grid"><section className="module-card"><h2>Verified doctors</h2>{list.length?list.map(d=><div className="directory-row" key={d.id}><span className="initials">{d.full_name?.slice(0,2)}</span><b>Dr. {d.full_name}</b><small>Verified specialist</small></div>):<p>Sign in to load available doctors.</p>}</section><section className="module-card"><h2>Request appointment</h2><form className="module-form" onSubmit={book}><select name="doctor" required><option value="">Choose a doctor</option>{list.map(d=><option value={d.id} key={d.id}>Dr. {d.full_name}</option>)}</select><input name="time" type="datetime-local" required/><textarea name="reason" placeholder="Reason for consultation" required/><button className="primary">Send request</button></form></section></div><div className="module-grid"><section className="module-card"><h2>Secure chat & file sharing</h2><p>Messages and attachments are stored inside your doctor conversation. Files are private and visible only to its participants.</p><button className="outline" onClick={()=>setMessage('Open an approved consultation from your dashboard to send chat messages and files.')}>Consultation messaging</button></section><section className="module-card"><h2>Voice & video consultation</h2><button className="primary" onClick={record}>{recording?'■ Stop voice note':'● Record voice note'}</button><button className="outline" onClick={()=>setMessage('Video consultation is ready for a Daily/Twilio provider key in the next deployment configuration.')}>▣ Start video consultation</button></section></div>{message&&<p className="auth-message">{message}</p>}</main></AppLayout> }
